import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")
FMP_API_KEY = os.getenv("FMP_API_KEY")
TECHNIC_API_KEY = os.getenv("TECHNIC_API_KEY")
SCOREBOARD_SYNC_URL = os.getenv("SCOREBOARD_SYNC_URL")
SCOREBOARD_SYNC_TOKEN = os.getenv("SCOREBOARD_SYNC_TOKEN")
SCOREBOARD_API_TOKEN = os.getenv("SCOREBOARD_API_TOKEN")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_USER_ID = os.getenv("SUPABASE_USER_ID")

